### PR TITLE
Add scss scope

### PR DESCRIPTION
**Pull request by mikem836**
Adds back support for scss syntax by including the `source.scss` scope in the 'selector' attribute.

### CODE REVIEW

**Comment by TomasBarry** [comment]
I'll test this out today and merge it in.

**Comment by TomasBarry** [comment]
Have confirmed locally that this does now also lint SCSS files and still lint SASS files. Happy to merge @skovhus?

**Comment by skovhus** [comment]
> Happy to merge @skovhus?

I'm happy if you are. :) To release you just create a tag here https://github.com/skovhus/SublimeLinter-contrib-sass-lint/releases ... As you see I try to fill in what changed.

**Comment by TomasBarry** [comment]
[Done](https://github.com/skovhus/SublimeLinter-contrib-sass-lint/releases/tag/1.3.1). Thanks @mikem836.

**Pull request merged**
