### PR TITLE
Impl vue embbeded support

### PR DESCRIPTION
**Pull request by lessmind**
fix for #19

### CODE REVIEW

**Comment by lukeheath** [comment]
@lessmind Thanks, this is great! Looking forward to using it.

**Comment by lessmind** [comment]
@skovhus Hi, is there anything I have to fix?
Seems ready to be merged now.

**Comment by skovhus** [comment]
I'm so sorry for leaving this here. Thanks for reminding me.

**Comment by lessmind** [comment]
Thanks a lot!

**Pull request merged**
